"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { DIMENSIONS } from "./dimensions";

interface AuditData {
  url: string;
  title: string | null;
  cqs: number | null;
  citability: number | null;
  scores: Record<string, number> | null;
  report: string | null;
  revisedContent: string | null;
  plan: string;
  createdAt: string;
}

// Color palette
const TEAL = "#14b8a6";
const HEADING_COLOR = "#1e293b";
const BODY_COLOR = "#334155";
const SECONDARY_COLOR = "#64748b";
const RED = "#ef4444";
const AMBER = "#f59e0b";
const GREEN = "#10b981";

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function getScoreColor(score: number): string {
  if (score <= 3) return RED;
  if (score <= 6) return AMBER;
  return GREEN;
}

function hexToRgb(hex: string): [number, number, number] {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return [0, 0, 0];
  return [
    parseInt(result[1], 16),
    parseInt(result[2], 16),
    parseInt(result[3], 16),
  ];
}

function addFooter(doc: jsPDF, pageNum: number, totalPages: number): void {
  const footerY = PAGE_HEIGHT - 12;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...hexToRgb(SECONDARY_COLOR));
  doc.text("Generated by CiteAudit | citeaudit.co", MARGIN, footerY);
  doc.text(
    `Page ${pageNum} of ${totalPages}`,
    PAGE_WIDTH - MARGIN,
    footerY,
    { align: "right" }
  );
}

function addAllFooters(doc: jsPDF): void {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_HEIGHT - 25) {
    doc.addPage();
    return MARGIN + 10;
  }
  return y;
}

interface ParsedLine {
  type: "heading" | "bold-line" | "bullet" | "table-row" | "text" | "empty";
  content: string;
  cells?: string[];
}

function parseMarkdownLines(markdown: string): ParsedLine[] {
  const lines = markdown.split("\n");
  const parsed: ParsedLine[] = [];

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed === "") {
      parsed.push({ type: "empty", content: "" });
      continue;
    }

    // Heading lines (## or ###)
    if (/^#{1,4}\s+/.test(trimmed)) {
      const content = trimmed.replace(/^#{1,4}\s+/, "");
      parsed.push({ type: "heading", content });
      continue;
    }

    // Table rows
    if (trimmed.startsWith("|") && trimmed.endsWith("|")) {
      // Skip separator rows like |---|---|
      if (/^\|[\s\-:|]+\|$/.test(trimmed)) continue;
      const cells = trimmed
        .split("|")
        .filter((c) => c.trim() !== "")
        .map((c) => c.trim());
      parsed.push({ type: "table-row", content: trimmed, cells });
      continue;
    }

    // Bullet points
    if (/^[-*]\s+/.test(trimmed)) {
      const content = trimmed.replace(/^[-*]\s+/, "");
      parsed.push({ type: "bullet", content: stripMarkdownInline(content) });
      continue;
    }

    // Bold entire line
    if (/^\*\*.*\*\*$/.test(trimmed)) {
      const content = trimmed.replace(/\*\*/g, "");
      parsed.push({ type: "bold-line", content });
      continue;
    }

    parsed.push({ type: "text", content: stripMarkdownInline(trimmed) });
  }

  return parsed;
}

function stripMarkdownInline(text: string): string {
  // Remove bold markers
  let result = text.replace(/\*\*(.*?)\*\*/g, "$1");
  // Remove italic markers
  result = result.replace(/\*(.*?)\*/g, "$1");
  // Remove inline code
  result = result.replace(/`(.*?)`/g, "$1");
  // Remove links, keep text
  result = result.replace(/\[(.*?)\]\(.*?\)/g, "$1");
  return result;
}

function renderMarkdownContent(
  doc: jsPDF,
  markdown: string,
  startY: number
): number {
  const lines = parseMarkdownLines(markdown);
  let y = startY;
  let tableBuffer: string[][] = [];

  function flushTable(): void {
    if (tableBuffer.length === 0) return;

    y = checkPageBreak(doc, y, 20 + tableBuffer.length * 8);

    const head = [tableBuffer[0]];
    const body = tableBuffer.slice(1);

    autoTable(doc, {
      startY: y,
      head,
      body,
      margin: { left: MARGIN, right: MARGIN },
      styles: {
        font: "helvetica",
        fontSize: 8,
        cellPadding: 3,
        textColor: hexToRgb(BODY_COLOR),
      },
      headStyles: {
        fillColor: hexToRgb(TEAL),
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      alternateRowStyles: {
        fillColor: [245, 247, 250],
      },
      theme: "grid",
    });

    // Get the final Y after the table
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable?.finalY ?? y + 30;
    y += 6;
    tableBuffer = [];
  }

  for (const line of lines) {
    // If we encounter a non-table line, flush any buffered table rows
    if (line.type !== "table-row" && tableBuffer.length > 0) {
      flushTable();
    }

    switch (line.type) {
      case "heading": {
        y = checkPageBreak(doc, y, 16);
        y += 8;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.setTextColor(...hexToRgb(HEADING_COLOR));
        doc.text(line.content, MARGIN, y);
        y += 7;
        break;
      }
      case "bold-line": {
        y = checkPageBreak(doc, y, 10);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(...hexToRgb(BODY_COLOR));
        const boldWrapped = doc.splitTextToSize(line.content, CONTENT_WIDTH);
        doc.text(boldWrapped, MARGIN, y);
        y += boldWrapped.length * 5 + 3;
        break;
      }
      case "bullet": {
        y = checkPageBreak(doc, y, 10);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(...hexToRgb(BODY_COLOR));
        const bulletText = doc.splitTextToSize(
          line.content,
          CONTENT_WIDTH - 10
        );
        doc.text("\u2022", MARGIN + 2, y);
        doc.text(bulletText, MARGIN + 8, y);
        y += bulletText.length * 5 + 2;
        break;
      }
      case "table-row": {
        if (line.cells) {
          tableBuffer.push(line.cells);
        }
        break;
      }
      case "text": {
        y = checkPageBreak(doc, y, 10);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(...hexToRgb(BODY_COLOR));
        const wrapped = doc.splitTextToSize(line.content, CONTENT_WIDTH);
        doc.text(wrapped, MARGIN, y);
        y += wrapped.length * 5 + 2;
        break;
      }
      case "empty": {
        y += 3;
        break;
      }
    }
  }

  // Flush any remaining table rows
  if (tableBuffer.length > 0) {
    flushTable();
  }

  return y;
}

export function generateAuditPDF(audit: AuditData): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // ─── PAGE 1: COVER / SUMMARY ──────────────────────────────

  // Brand header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);
  doc.setTextColor(...hexToRgb(TEAL));
  doc.text("CiteAudit", MARGIN, 40);

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(16);
  doc.setTextColor(...hexToRgb(HEADING_COLOR));
  doc.text("Content Audit Report", MARGIN, 52);

  // Divider line
  doc.setDrawColor(...hexToRgb(TEAL));
  doc.setLineWidth(0.8);
  doc.line(MARGIN, 58, PAGE_WIDTH - MARGIN, 58);

  // URL
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...hexToRgb(SECONDARY_COLOR));
  doc.text("URL Audited", MARGIN, 72);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...hexToRgb(BODY_COLOR));
  const wrappedUrl = doc.splitTextToSize(audit.url, CONTENT_WIDTH);
  doc.text(wrappedUrl, MARGIN, 78);

  // Date
  const dateY = 78 + wrappedUrl.length * 5 + 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...hexToRgb(SECONDARY_COLOR));
  doc.text("Date of Audit", MARGIN, dateY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...hexToRgb(BODY_COLOR));
  const formattedDate = new Date(audit.createdAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(formattedDate, MARGIN, dateY + 6);

  // Title (if available)
  let scoreStartY = dateY + 30;
  if (audit.title) {
    const titleY = dateY + 20;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...hexToRgb(SECONDARY_COLOR));
    doc.text("Page Title", MARGIN, titleY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...hexToRgb(BODY_COLOR));
    const wrappedTitle = doc.splitTextToSize(audit.title, CONTENT_WIDTH);
    doc.text(wrappedTitle, MARGIN, titleY + 6);
    scoreStartY = titleY + 6 + wrappedTitle.length * 5 + 16;
  }

  // CQS Score (large display)
  const cqsBoxX = MARGIN;
  const cqsBoxY = scoreStartY;
  const boxWidth = 78;
  const boxHeight = 55;

  doc.setFillColor(245, 247, 250);
  doc.roundedRect(cqsBoxX, cqsBoxY, boxWidth, boxHeight, 4, 4, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...hexToRgb(SECONDARY_COLOR));
  doc.text("Content Quality Score (CQS)", cqsBoxX + boxWidth / 2, cqsBoxY + 12, {
    align: "center",
  });

  const cqsValue = audit.cqs !== null ? String(audit.cqs) : "N/A";
  const cqsColor =
    audit.cqs !== null ? getScoreColor(audit.cqs / 10) : SECONDARY_COLOR;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(36);
  doc.setTextColor(...hexToRgb(cqsColor));
  doc.text(cqsValue, cqsBoxX + boxWidth / 2, cqsBoxY + 37, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...hexToRgb(SECONDARY_COLOR));
  doc.text("out of 100", cqsBoxX + boxWidth / 2, cqsBoxY + 47, {
    align: "center",
  });

  // AI Citability Score
  const citBoxX = MARGIN + boxWidth + 14;
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(citBoxX, cqsBoxY, boxWidth, boxHeight, 4, 4, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...hexToRgb(SECONDARY_COLOR));
  doc.text("AI Citability Score", citBoxX + boxWidth / 2, cqsBoxY + 12, {
    align: "center",
  });

  const citValue =
    audit.citability !== null ? `${audit.citability}%` : "N/A";
  const citColor =
    audit.citability !== null
      ? getScoreColor(audit.citability / 10)
      : SECONDARY_COLOR;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(36);
  doc.setTextColor(...hexToRgb(citColor));
  doc.text(citValue, citBoxX + boxWidth / 2, cqsBoxY + 37, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...hexToRgb(SECONDARY_COLOR));
  doc.text("likelihood of citation", citBoxX + boxWidth / 2, cqsBoxY + 47, {
    align: "center",
  });

  // ─── PAGE 2: DIMENSION SCORES ─────────────────────────────

  doc.addPage();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...hexToRgb(HEADING_COLOR));
  doc.text("Dimension Scores", MARGIN, 30);

  doc.setDrawColor(...hexToRgb(TEAL));
  doc.setLineWidth(0.6);
  doc.line(MARGIN, 34, PAGE_WIDTH - MARGIN, 34);

  const tableBody = DIMENSIONS.map((dim, idx) => {
    const score =
      audit.scores && audit.scores[dim.key] !== undefined
        ? audit.scores[dim.key]
        : null;
    return [
      String(idx + 1),
      dim.acronym || "-",
      dim.fullName,
      score !== null ? `${score}/10` : "N/A",
      dim.whyItMatters,
    ];
  });

  autoTable(doc, {
    startY: 40,
    head: [["#", "Acronym", "Dimension", "Score", "Why It Matters"]],
    body: tableBody,
    margin: { left: MARGIN, right: MARGIN },
    styles: {
      font: "helvetica",
      fontSize: 8,
      cellPadding: 3,
      textColor: hexToRgb(BODY_COLOR),
      lineColor: [220, 225, 232],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: hexToRgb(TEAL),
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8.5,
    },
    columnStyles: {
      0: { cellWidth: 8, halign: "center" },
      1: { cellWidth: 18, halign: "center" },
      2: { cellWidth: 42 },
      3: { cellWidth: 16, halign: "center", fontStyle: "bold" },
      4: { cellWidth: "auto", fontStyle: "normal" },
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    theme: "grid",
    didParseCell: (data) => {
      // Color-code the score column
      if (data.column.index === 3 && data.section === "body") {
        const text = data.cell.raw as string;
        const match = text.match(/^(\d+)\/10$/);
        if (match) {
          const val = parseInt(match[1], 10);
          data.cell.styles.textColor = hexToRgb(getScoreColor(val));
        }
      }
    },
  });

  // ─── PAGE 3+: DETAILED ANALYSIS ──────────────────────────

  if (audit.report) {
    doc.addPage();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(...hexToRgb(HEADING_COLOR));
    doc.text("Detailed Analysis", MARGIN, 30);

    doc.setDrawColor(...hexToRgb(TEAL));
    doc.setLineWidth(0.6);
    doc.line(MARGIN, 34, PAGE_WIDTH - MARGIN, 34);

    renderMarkdownContent(doc, audit.report, 44);
  }

  // ─── FINAL PAGES: REVISED ARTICLE (Pro only) ─────────────

  if (audit.revisedContent && audit.plan === "pro") {
    doc.addPage();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(...hexToRgb(HEADING_COLOR));
    doc.text("Revised Article", MARGIN, 30);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...hexToRgb(SECONDARY_COLOR));
    doc.text(
      "AI-optimized version with all recommendations implemented",
      MARGIN,
      38
    );

    doc.setDrawColor(...hexToRgb(TEAL));
    doc.setLineWidth(0.6);
    doc.line(MARGIN, 43, PAGE_WIDTH - MARGIN, 43);

    renderMarkdownContent(doc, audit.revisedContent, 52);
  }

  // ─── ADD FOOTERS TO ALL PAGES ─────────────────────────────

  addAllFooters(doc);

  // ─── TRIGGER DOWNLOAD ─────────────────────────────────────

  const sanitizedUrl = audit.url
    .replace(/^https?:\/\//, "")
    .replace(/[^a-zA-Z0-9]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);

  const dateStr = new Date(audit.createdAt)
    .toISOString()
    .split("T")[0];

  doc.save(`citeaudit-audit-${sanitizedUrl}-${dateStr}.pdf`);
}
